# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 619d4ff4e9b78d3eabade7c63c95d9031888902ddad84be0fce6123da3dbe9da5d1505a3f028d0c4d1dbaff09a9e4739d5a1d97817a450ee47716fbf8c7fabc4

test:
  secret_key_base: 954d5eebea59c0a2f86b920ffd1a8d3ec3141551325fa7c12131fcdf660f25da864981106cca2fef99ff754a6d0a35da5903c335758abc9fcfa47c4c022fe2e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
